#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StackSnapMvvmCross.Droid.Resource", IsApplication=true)]

namespace StackSnapMvvmCross.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::StackSnapMvvmCross.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::StackSnapMvvmCross.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scalewelcometext = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int action_bar_color = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int actionbarcolor = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int custom_theme_color = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int darkgray = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int gray = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int lightgray = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int opaque_red = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int row_color_selected = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int row_color_unselected = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int textlightblue = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int translucent_red = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int borderGrayed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_custom = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_disabled_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_enabled_style = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int camera = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cbchk = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cbunchk = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int checkboxtheme = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int color_cursor = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int createstack = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int delete = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int deleteImage = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int forestBackground = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int GPS_NOK = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int GPS_OK = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int LoginLogo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int logout = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int PlaceHolder = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int save = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Sendmessage = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner_76_inner_holo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_76_inner_holo_small = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_76_outer_holo = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_76_outer_holo_small = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int splash = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int splash_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int SplashScreen = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int SplashScreenSmall = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int sScaleLogo = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sScaleLogo2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int styles = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080014
			public const int FooterLayout = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int LoginLogo = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int MvxBindingTagUnique = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int MyButton = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int Processing = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int ProgressSpinner = 2131230745;
			
			// aapt resource value: 0x7f080006
			public const int ScrollView = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int ServerIdLabel = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int UserNameLabel = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int aboutButton = 2131230744;
			
			// aapt resource value: 0x7f080003
			public const int applicationId = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int checkBoxFrame = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int checkBoxText = 2131230737;
			
			// aapt resource value: 0x7f08001b
			public const int filler = 2131230747;
			
			// aapt resource value: 0x7f080007
			public const int footer = 2131230727;
			
			// aapt resource value: 0x7f080016
			public const int infoText = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int loginButton = 2131230743;
			
			// aapt resource value: 0x7f080012
			public const int passwordLabel = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int passwordText = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int passwordcheckbox = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int passworddesc = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int serverIdText = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int space = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int spinnerServerId = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int spinnerUsername = 2131230733;
			
			// aapt resource value: 0x7f080015
			public const int strut = 2131230741;
			
			// aapt resource value: 0x7f080005
			public const int textViewWelcome = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int userNameText = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int welcomeImageView = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FirstView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashScreen = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060035
			public const int APIErrorText = 2131099701;
			
			// aapt resource value: 0x7f060017
			public const int AcceptText = 2131099671;
			
			// aapt resource value: 0x7f060002
			public const int AppName = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int CameraText = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int CancelText = 2131099672;
			
			// aapt resource value: 0x7f060037
			public const int DeleteReqText = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int DeleteText = 2131099704;
			
			// aapt resource value: 0x7f060020
			public const int DepthText = 2131099680;
			
			// aapt resource value: 0x7f06003c
			public const int DraftText = 2131099708;
			
			// aapt resource value: 0x7f060044
			public const int EmptyListReqText = 2131099716;
			
			// aapt resource value: 0x7f06001b
			public const int GetPictureText = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int GoodEveningText = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int GoodMorningText = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int Goodbye = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int HelloText = 2131099651;
			
			// aapt resource value: 0x7f06001d
			public const int KindText = 2131099677;
			
			// aapt resource value: 0x7f060011
			public const int LoadingDataText = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int LoadingPictureText = 2131099666;
			
			// aapt resource value: 0x7f060043
			public const int LoggingOnText = 2131099715;
			
			// aapt resource value: 0x7f06000c
			public const int LoginText = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int NewStackText = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int NoConnectionText = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int NoConnectionYourDataSavedText = 2131099655;
			
			// aapt resource value: 0x7f060026
			public const int NoGeoCoordinatesText = 2131099686;
			
			// aapt resource value: 0x7f060036
			public const int NonUniqueIdText = 2131099702;
			
			// aapt resource value: 0x7f06001e
			public const int NoneHintText = 2131099678;
			
			// aapt resource value: 0x7f060008
			public const int NotAllDataContinueText = 2131099656;
			
			// aapt resource value: 0x7f06003d
			public const int NotAllDataIsAvailableText = 2131099709;
			
			// aapt resource value: 0x7f06003b
			public const int NotSentText = 2131099707;
			
			// aapt resource value: 0x7f060023
			public const int NotesText = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int NotesTextMax = 2131099684;
			
			// aapt resource value: 0x7f060009
			public const int PasswordText = 2131099657;
			
			// aapt resource value: 0x7f060039
			public const int SaveText = 2131099705;
			
			// aapt resource value: 0x7f060010
			public const int Send = 2131099664;
			
			// aapt resource value: 0x7f060042
			public const int SendConfirmText = 2131099714;
			
			// aapt resource value: 0x7f060041
			public const int SendText = 2131099713;
			
			// aapt resource value: 0x7f06003a
			public const int SentText = 2131099706;
			
			// aapt resource value: 0x7f06000b
			public const int ServerIdText = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int SomethingWentWrongText = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int SpeciesText = 2131099676;
			
			// aapt resource value: 0x7f060040
			public const int StackDataSavedText = 2131099712;
			
			// aapt resource value: 0x7f06003f
			public const int StackDataSentSuccessText = 2131099711;
			
			// aapt resource value: 0x7f060015
			public const int StackHistoryText = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int StackIdText = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int StatusText = 2131099682;
			
			// aapt resource value: 0x7f06003e
			public const int TimeText = 2131099710;
			
			// aapt resource value: 0x7f060033
			public const int UnAuthorizedText = 2131099699;
			
			// aapt resource value: 0x7f06001a
			public const int UploadingText = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int UserUploadText = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int UsernameText = 2131099658;
			
			// aapt resource value: 0x7f06001f
			public const int VolumeText = 2131099679;
			
			// aapt resource value: 0x7f06000f
			public const int Welcome = 2131099663;
			
			// aapt resource value: 0x7f060034
			public const int WrongServerText = 2131099700;
			
			// aapt resource value: 0x7f06000d
			public const int aboutText = 2131099661;
			
			// aapt resource value: 0x7f06002d
			public const int destinationText = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int eidText = 2131099691;
			
			// aapt resource value: 0x7f060032
			public const int emptyListText = 2131099698;
			
			// aapt resource value: 0x7f060025
			public const int errorPictureText = 2131099685;
			
			// aapt resource value: 0x7f060031
			public const int gpsText = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int missingLocationText = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int missingStackIdText = 2131099696;
			
			// aapt resource value: 0x7f06002a
			public const int showpasswordsText = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int sourceText = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int workingText = 2131099694;
			
			// aapt resource value: 0x7f060027
			public const int wrongCredentialsText = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int wrongDepthText = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int wrongVolumeText = 2131099688;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int ButtonStyle = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int ButtonTextStyle = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int CodeFont = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int CustomTheme = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int button_text = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int progress = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int scalewelcometext = 2131034113;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
